WebCrawlerApplication/Controllers/CrawlerStartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebCrawlerApplication.Data;
using WebCrawlerApplication.Models;
using WebCrawlerApplication.Repositories;
using WebCrawlerApplication.Services;

namespace WebCrawlerApplication.Controllers
{
    public class CrawlerStartController : Controller
    {
        private readonly ICrawlerSearchService _crawlerSearchService;

        public CrawlerStartController(ICrawlerSearchService crawlerSearchService)
        {
            _crawlerSearchService = crawlerSearchService;
        }

        // GET: CrawlerStart
        public async Task<IActionResult> Index()
        {
            return View();
        }

        //// GET: CrawlerStart/Details/5
        //public async Task<IActionResult> Details(string id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var crawlerStartModel = await _context.CrawlerStartModel
        //        .FirstOrDefaultAsync(m => m.URL == id);
        //    if (crawlerStartModel == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(crawlerStartModel);
        //}

        // GET: CrawlerStart/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: CrawlerStart/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("URL,Expression,Depth")] CrawlerStartModel crawlerStartModel)
        {
            if (crawlerStartModel.Depth==null)
                crawlerStartModel.Depth = 1;

            if (ModelState.IsValid)
            {
                await _crawlerSearchService.CrawlerStart(crawlerStartModel);
                return RedirectToAction(nameof(Finish));
            }
            return View(crawlerStartModel);
        }

        public IActionResult Finish()
        {
            return View();
        }

    }
}

WebCrawlerApplication/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebCrawlerApplication.Data;
using WebCrawlerApplication.Models;
using WebCrawlerApplication.Services;

namespace WebCrawlerApplication.Controllers
{
    public class LoginController : Controller
    {
        private readonly IUserService _userService;

        public LoginController(IUserService userService)
        {
            _userService = userService;
        }

        // GET: Login
        public async Task<IActionResult> Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index([Bind("Email,Password")] LoginModel loginModel)
        {
            if (ModelState.IsValid)
            {
                if (await _userService.DoesUserExist(loginModel))
                {
                    return RedirectToAction("Index", "Home");
                }
            }

            return View();
        }

        public async Task<IActionResult> Logout()
        {       
            Response.Cookies.Delete("Email");
            return RedirectToAction(nameof(Index));
        }
    }
}

WebCrawlerApplication/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebCrawlerApplication.Data;
using WebCrawlerApplication.Models;
using WebCrawlerApplication.Repositories;
using WebCrawlerApplication.Services;

namespace WebCrawlerApplication.Controllers
{
    public class ReportController : Controller
    {
        private readonly ICrawlerSearchService _crawlerSearchService;

        public ReportController(ICrawlerSearchService crawlerSearchService)
        {
            _crawlerSearchService = crawlerSearchService;
        }

        // GET: Report
        public async Task<IActionResult> Index()
        {
            return View(await _crawlerSearchService.GetCrawlerSearches());
        }

        //// GET: Report/Details/5
        //public async Task<IActionResult> Details(string id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var reportModel = await _context.ReportModel
        //        .FirstOrDefaultAsync(m => m.Crawlername == id);
        //    if (reportModel == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(reportModel);
        //}

        //// GET: Report/Create
        //public IActionResult Create()
        //{
        //    return View();
        //}

        //// POST: Report/Create
        //// To protect from overposting attacks, enable the specific properties you want to bind to, for 
        //// more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create([Bind("Crawlername,Date,URL,Expression,HitCount")] ReportModel reportModel)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _context.Add(reportModel);
        //        await _context.SaveChangesAsync();
        //        return RedirectToAction(nameof(Index));
        //    }
        //    return View(reportModel);
        //}

        //// GET: Report/Edit/5
        //public async Task<IActionResult> Edit(string id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var reportModel = await _context.ReportModel.FindAsync(id);
        //    if (reportModel == null)
        //    {
        //        return NotFound();
        //    }
        //    return View(reportModel);
        //}

        //// POST: Report/Edit/5
        //// To protect from overposting attacks, enable the specific properties you want to bind to, for 
        //// more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Edit(string id, [Bind("Crawlername,Date,URL,Expression,HitCount")] ReportModel reportModel)
        //{
        //    if (id != reportModel.Crawlername)
        //    {
        //        return NotFound();
        //    }

        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            _context.Update(reportModel);
        //            await _context.SaveChangesAsync();
        //        }
        //        catch (DbUpdateConcurrencyException)
        //        {
        //            if (!ReportModelExists(reportModel.Crawlername))
        //            {
        //                return NotFound();
        //            }
        //            else
        //            {
        //                throw;
        //            }
        //        }
        //        return RedirectToAction(nameof(Index));
        //    }
        //    return View(reportModel);
        //}

        //// GET: Report/Delete/5
        //public async Task<IActionResult> Delete(string id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var reportModel = await _context.ReportModel
        //        .FirstOrDefaultAsync(m => m.Crawlername == id);
        //    if (reportModel == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(reportModel);
        //}

        //// POST: Report/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> DeleteConfirmed(string id)
        //{
        //    var reportModel = await _context.ReportModel.FindAsync(id);
        //    _context.ReportModel.Remove(reportModel);
        //    await _context.SaveChangesAsync();
        //    return RedirectToAction(nameof(Index));
        //}

        //private bool ReportModelExists(string id)
        //{
        //    return _context.ReportModel.Any(e => e.Crawlername == id);
        //}
    }
}

WebCrawlerApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebCrawlerApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebCrawlerApplication</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CrawlerStart" asp-action="Create">Start New Crawler</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Report" asp-action="Index">Reports</a>
                        </li>
                        <li class="nav-item" style="width:70%">
                            <a style="float:right" class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Logout">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WebCrawlerApplication 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>